# Generated by Django 3.1.2 on 2020-11-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_insumo_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='imagen',
            field=models.ImageField(null=True, upload_to='servicio'),
        ),
    ]
