# Generated by Django 3.1.2 on 2020-11-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_galeria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nosotros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('nosotros', models.TextField()),
                ('historia', models.TextField()),
                ('mision', models.TextField()),
                ('vision', models.TextField()),
            ],
        ),
    ]
