# Generated by Django 3.1.2 on 2020-11-05 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20201105_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='rut',
        ),
    ]
