# Generated by Django 3.1.2 on 2020-12-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20201209_0332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('asunto', models.CharField(max_length=50)),
                ('tipo_contacto', models.IntegerField(choices=[[1, 'sugerencia'], [2, 'reclamo'], [3, 'consulta']])),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
